Added message event. Added anyUpdate event
TelegramBot/Api pull request #292
Opened 2020-10-24 11:50 UTC by EbashuOnHolidays

Добавил метод `message` который необходим для получения всех входящих сообщений (включая произвольный текст), на ряду с `callbackQuery` и другими типами сообщений отправляемых Телеграмом.

```php
$client->message(function (Message $message) {
      //...
});
```

Добавил метод `anyUpdate` который отслеживает любое сообщение полученное системой.

```php
$client->anyUpdate(function ($request) {
      $from = $request->getFrom();

      // ...
      // make authorization for incoming request
      // ...
});
```

2020-10-24 21:32 UTC, BoShurik requested changes
Не хвататет тестов

2020-10-24 21:32 UTC, BoShurik commented on src/Client.php
> -    protected static function getEvent(Closure $action)
Т.к. метод protected, то это BC bracke

2020-10-24 21:32 UTC, BoShurik commented on src/Client.php
> -    protected static function getChecker($name)
Аналогично `getEvent`

2020-10-24 21:35 UTC, BoShurik commented
Собственно тесты от этого и упали... Пока от меня 👎

2020-10-26 09:02 UTC, BoShurik requested changes
Ревертни, пожалуйста, не связанные изменения (изменение порядка методов, удаление лишних пробелов etc)

2020-10-29 10:20 UTC, EbashuOnHolidays commented
@BoShurik готово

2020-10-29 10:31 UTC, BoShurik commented on src/Client.php
> +    public function anyUpdate(Closure $action)
В чем разница с `Client::on($action)`?

2020-10-29 11:00 UTC, EbashuOnHolidays commented on src/Client.php
> +    public function anyUpdate(Closure $action)
Подскажи пожалуйста как я могу через метод `on` запустить свой Closure для абсолютно всех входящих веб-хуков?

Я вижу только такой вариант, и он мне не подходит так как работает исключительно с `$update->getMessage()`
```php
$this->client->on(function (Update $update) {
    $reflectionAction = new ReflectionFunction($this->loginUser());
    $reflectionAction->invokeArgs([$update->getMessage()]);

    return false;
}, function () {
    return true;
});

$this->client->run();
```

2020-10-29 11:21 UTC, BoShurik commented on src/Client.php
> +    public function anyUpdate(Closure $action)
Ты же сам ограничил запускаешь каллбек с `$update->getMessage()`
`$reflectionAction->invokeArgs([$update->getMessage()]);`

```php
$bot->on(function (Update $update) use ($bot) {
    $chat = ''; // Get chat id from $update
    $bot->sendMessage($chat, $update->toJson());
}, fn () => true);
```

2020-10-29 11:35 UTC, EbashuOnHolidays commented on src/Client.php
> +    public function anyUpdate(Closure $action)
Я вот только не вижу какой именно метод в классе Update отвечает за получение chat id?

2020-10-29 11:38 UTC, EbashuOnHolidays commented on src/Client.php
> +    public function anyUpdate(Closure $action)
В классе Update есть только описание типов получаемых хуков:
Message, InlineQuery, ChosenInlineResult, CallbackQuery, ShippingQuery, PreCheckoutQuery, PollAnswer, Poll

Получив тип хука я могу вытащить getFrom и chat id. То есть мне написать switch case и следить за очередными изменениям в документации Телеграма когда они решат добавить еще один или несколько типов хуков?

2020-10-29 11:39 UTC, BoShurik commented on src/Client.php
> +    public function anyUpdate(Closure $action)
Это зависит от ивента:
```php
$chat = $update->getMessage()->getChat()->getId();
$chat = $update->getCallbackQuery()->getMessage()->getChat()->getId();
```

2020-10-29 11:59 UTC, BoShurik commented on src/Client.php
> +    public function anyUpdate(Closure $action)
Выходит так на так:
```php
$bot->on(function (Update $update) use ($bot) {
    switch (true) {
        case $update->getMessage() !== null:
            $chat = $update->getMessage()->getChat()->getId();
            break;
        case $update->getCallbackQuery() !== null:
            $chat = $update->getCallbackQuery()->getMessage()->getChat()->getId();
            break;
        // ...
    }
    $bot->sendMessage($chat, $update->toJson());
}, fn () => true);
```
```php
$bot->on(function ($update) use ($bot) {
    switch (true) {
        case $update instanceof Message:
            $chat = $update->getChat()->getId();
            break;
        case $update instanceof CallbackQuery:
            $chat = $update->getMessage()->getChat()->getId();
            break;
        // ...
    }
    $bot->sendMessage($chat, $update->toJson());
});
```
Но в твоем варианте эти проверки дополнительно проверяются под капотом на каждую команду в `EventCollection`

2020-10-29 12:00 UTC, EbashuOnHolidays commented on src/Client.php
> +    public function anyUpdate(Closure $action)
Метод `anyUpdate(Closure $action)` сработает вне зависимости от ивента, условия проверки писать не придётся, так как это уже реализовано в самой библиотеке

И тут получается следующее:
```php
private function loginUser()
{
    return function ($request) {
        $from = $request->getFrom();

        //.......
    };
}

Вместо:

```php
$bot->on(function (Update $update) use ($bot) {
    if ($update->getMessage()) {
        $chat = $update->getMessage()->getFrom();
    }

    if ($update->getEditedMessage()) {
        $chat = $update->getEditedMessage()->getFrom();
    }

    if ($update->getChannelPost()) {
        $chat = $update->getChannelPost()->getFrom();
    }

    if ($update->getPollAnswer()) {
        $chat = $update->getPollAnswer()->getFrom();
    }

    if ($update->getPoll()) {
        $chat = $update->getMessage()->getFrom();
    }

    if ($update->getEditedChannelPost()) {
        $chat = $update->getEditedChannelPost()->getFrom();
    }

    if ($update->getInlineQuery()) {
        $chat = $update->getInlineQuery()->getFrom();
    }

    if ($update->getChosenInlineResult()) {
        $chat = $update->getChosenInlineResult()->getFrom();
    }

    if ($update->getCallbackQuery()) {
        $chat = $update->getCallbackQuery()->getFrom();
    }

    if ($update->getShippingQuery()) {
        $chat = $update->getShippingQuery()->getFrom();
    }

    if ($update->getPreCheckoutQuery()) {
        $chat = $update->getPreCheckoutQuery()->getFrom();
    }

    // ...............
}, fn () => true);
```

2020-10-29 12:08 UTC, EbashuOnHolidays commented on src/Client.php
> +    public function anyUpdate(Closure $action)
> Выходит так на так:
> 
> ```
> $bot->on(function (Update $update) use ($bot) {
>     switch (true) {
>         case $update->getMessage() !== null:
>             $chat = $update->getMessage()->getChat()->getId();
>             break;
>         case $update->getCallbackQuery() !== null:
>             $chat = $update->getCallbackQuery()->getMessage()->getChat()->getId();
>             break;
>         // ...
>     }
>     $bot->sendMessage($chat, $update->toJson());
> }, fn () => true);
> ```
> 
> ```
> $bot->on(function ($update) use ($bot) {
>     switch (true) {
>         case $update instanceof Message:
>             $chat = $update->getChat()->getId();
>             break;
>         case $update instanceof CallbackQuery:
>             $chat = $update->getMessage()->getChat()->getId();
>             break;
>         // ...
>     }
>     $bot->sendMessage($chat, $update->toJson());
> });
> ```
> 
> Но в твоем варианте эти проверки дополнительно проверяются под капотом на каждую команду в `EventCollection`

Как бы да, в одном месте я пропишу это статично, но таскать такое из проекта в проект и следить за тем что "вдруг появился новый instanceof, надо проверить" - ну это слишком

2020-10-29 12:08 UTC, BoShurik commented on src/Client.php
> +    public function anyUpdate(Closure $action)
`getFrom()` возвращает пользователя, а не чат, в который нужно послать ответ. Плюс, для `poll` и `poll_answer` этого метода нет.

2020-10-29 12:20 UTC, EbashuOnHolidays commented on src/Client.php
> +    public function anyUpdate(Closure $action)
`poll` да, нету, но poll имеет тип `Message` по этому из сообщения можно вытащить getFrom()
а вот у `poll_answer` [есть метод](https://github.com/TelegramBot/Api/blob/master/src/Types/PollAnswer.php#L87), IDE на него не ругается

2021-04-25 20:27 UTC, VChernomYA commented
https://github.com/TelegramBot/Api/pull/292/files

2021-04-25 20:28 UTC, VChernomYA commented
https://github.com/TelegramBot/Api/commit/91a17a3bea9a90af954ec09f98250858a1ce9305

2021-04-25 20:28 UTC, VChernomYA commented
https://github.com/TelegramBot/Api/commit/91a17a3bea9a90af954ec09f98250858a1ce9305

2023-06-25 03:03 UTC, closed without merging