fix json_encode in BotApi class setMyCommands method
TelegramBot/Api pull request #405
Opened 2023-04-17 12:12 UTC by eerzho

I noticed that in the `BotApi` class, an error occurs in the `setMyCommands` method when the code executes `json_encode($commands)`, returning empty objects in JSON and causing a BadRequest error from the Telegram API. To fix this error, I added implements of the `JsonSerializable` interface to the `BotCommand` class. Now when we call `json_encode($commands)` we get valid JSON.

2023-04-22 10:18 UTC, bernard-ng requested changes
Hello @eerzho `BotCommand` extends from `BaseType` which as a `toJson()` method, not need to implement JsonSerializable and add ext-json as a requirement.

2023-04-22 20:28 UTC, eerzho commented
Hi @bernard-ng!
I created several objects of the BotCommand class and passed an array to the setMyCommands method. My command returned an error, I looked at what is sent to body. And I saw that the request body is filled with empty objects.
Maybe I'm doing something wrong...

2023-04-24 12:57 UTC, BoShurik commented
There is class `TelegramBot\Api\Types\ArrayOfBotCommand`
```php
$commands = ArrayOfBotCommand();
$commands->add($command);
$api->setMyCommands($commands);
```

And in api there must be
```
return $this->call(
    'setMyCommands',
    [
        'commands' => $commands->toJson(),
    ]
);
```

Can you fix this?

2023-04-26 16:13 UTC, closed without merging

2023-04-26 21:37 UTC, eerzho commented
Hi @BoShurik 
Yes it helped, thanks a lot